### ISSUE TITLE
Umbral Donation

### ISSUE THREAD

**Issue by wsdmatty** [Haven-of-the-Embraced/src#102]
---

Author Name: **Nicholas** (Nicholas)
Original Redmine Issue: 82, https://havenmud.net/tracker/issues/82
Original Date: 2020-01-11
Original Assignee: Matthew

---

I tried to donate an obj in my inventory while I was in the Umbra, and the MUD crashed.  Coincidence?  Probably not.   It was an object I brought over from the 'real world' and got the umbra flag from me stepping sideways as Moc.  Specifically, it was a lotus chain from Castle Sengir.

**Comment by RedRobeGilean** [comment]
Already fixed with a prior change, preventing donating while Umbral.
