### ISSUE TITLE
Flagfind Additions - Objs

### ISSUE THREAD

**Issue by wsdmatty** [Haven-of-the-Embraced/src#105]
---

Author Name: **Matthew** (Matthew)
Original Redmine Issue: 86, https://havenmud.net/tracker/issues/86
Original Date: 2020-01-05
Original Assignee: Matthew

---

> Can we add more options for flagfind?  It would give us more options when trying to track down vnums when we need to alter or remove things that are obsolete or incorrect.  My initial ones that I feel most useful would be for mobs.  Can we add Act, Act2, Off, Level, etc?   Similar ones for objs could be helpful too.  Rooms not as much because we already have sector/room options.

Need list of useful options for flagfind on OBJs. Currently we have extra, wear, affect, damage, type, weapon, special, spell.

Level would be useful. Really the only one I can think of.

**Comment by RedRobeGilean** [comment]
size and cost as well
