### ISSUE TITLE
Flagfind Additions - Rooms

### ISSUE THREAD

**Issue by wsdmatty** [Haven-of-the-Embraced/src#106]
---

Author Name: **Matthew** (Matthew)
Original Redmine Issue: 87, https://havenmud.net/tracker/issues/87
Original Date: 2020-01-05
Original Assignee: Nicholas

---

> Can we add more options for flagfind?  It would give us more options when trying to track down vnums when we need to alter or remove things that are obsolete or incorrect.  My initial ones that I feel most useful would be for mobs.  Can we add Act, Act2, Off, Level, etc?   Similar ones for objs could be helpful too.  Rooms not as much because we already have sector/room options.

I can see a few useful room options.

Noexits (rooms with no exits, duh)
Heal/Mana (Rooms with modified heal/mana rates)

Maybe that's it.

**Comment by RedRobeGilean** [comment]
Clan / Owner flags
