### ISSUE TITLE
inspect lock command

### ISSUE THREAD

**Issue by wsdmatty** [Haven-of-the-Embraced/src#113]
---

Author Name: **Anonymous** (Anonymous)
Original Redmine Issue: 95, https://havenmud.net/tracker/issues/95
Original Date: 2020-02-03
Original Assignee: Matthew

---

It would be nice to have some sort of command to inspect the locks on doors to find out if they are pickable, poppable, or "enchanted" to require a specific key no matter what.

**Comment by RedRobeGilean** [comment]
Already implemented with prior 'examine' update.
