### ISSUE TITLE
sultan's assassin in damascus

### ISSUE THREAD

**Issue by wsdmatty** [Haven-of-the-Embraced/src#124]
---

Author Name: **Jack** (Jack)
Original Redmine Issue: 106, https://havenmud.net/tracker/issues/106
Original Date: 2020-02-16
Original Assignee: Matthew

---

the assassin's lag proc continues triggering indefinitely, even when the assassin is stunned/knocked out

**Comment by RedRobeGilean** [comment]
already fixed
