### ISSUE TITLE
Certain mobs need immunity to disarm 

### ISSUE THREAD

**Issue by wsdmatty** [Haven-of-the-Embraced/src#82]
---

Author Name: **Matthew** (Matthew)
Original Redmine Issue: 61, https://havenmud.net/tracker/issues/61
Original Date: 2019-03-30
Original Assignee: Matthew

---

Grimnir disarmed the Veteran and got the godly axe for free.

Possibly add an immunity flag, immune to disarm, for boss mobs.

**Comment by wsdmatty** [comment]
Solved by adding #27 iron grip, immunity to disarm

**Comment by RedRobeGilean** [comment]
Immune to disarm already coded.
