### ISSUE TITLE
Blackdeath

### ISSUE THREAD

**Issue by wsdmatty** [Haven-of-the-Embraced/src#83]
---

Author Name: **Matthew** (Matthew)
Original Redmine Issue: 62, https://havenmud.net/tracker/issues/62
Original Date: 2019-03-30
Original Assignee: Matthew

---

Blackdeath allows Grimnir to insta-kill Lag Beast.

This is wrong.

**Comment by RedRobeGilean** [comment]
Just needs an ifcheck to prevent use against ultra mob.
