### ISSUE TITLE
Give Mages a way to detect Unseen

### ISSUE THREAD

**Issue by wsdmatty** [Haven-of-the-Embraced/src#89]
---

Author Name: **Matthew** (Matthew)
Original Redmine Issue: 69, https://havenmud.net/tracker/issues/69
Original Date: 2020-01-03
Original Assignee: Matthew

---

Currently Mages do not have a way of detecting through Obfuscate Unseen, which is on like, five mobs, tops. 

More than one player has asked about ways to remedy this. Shaori and I discussed Mind vs Obfuscate as a way to give Mages a detect_unseen affect. This seems the most likely way to go about it.

**Comment by RedRobeGilean** [comment]
Add detect unseen to camouflage discernment combo rote.
