### ISSUE TITLE
Color bleed when viewing Resets

### ISSUE THREAD

**Issue by wsdmatty** [Haven-of-the-Embraced/src#99]
---

Author Name: **Nicholas** (Nicholas)
Original Redmine Issue: 79, https://havenmud.net/tracker/issues/79
Original Date: 2020-01-09
Original Assignee: Matthew

---

Room:  31

When you view the resets, since the room has color in the code of its name, it bleeds onto the next line and doesn't clear.  This specifically from a reset that loads obj into room itself, hence the room name showing in reset.  I doublechecked and changed the room name and ensured a {x clear code at the end of it.  I even removed the resets, redid them to test, and still got the bleed.  Perhaps it truncates and doesn't register the end clear code?

**Comment by RedRobeGilean** [comment]
Fixed.
